- name: Creating Virtual Servers
  hosts: all
  gather_facts: no
  tasks:
  - name: Build instance request
    sl_vm:
      hostname: "{{ inventory_hostname }}"
      domain: icp.local
      datacenter: sao01
      tags: icp demo
      hourly: yes
      private: no
      dedicated: no
      local_disk: yes
      cpus: 4
      memory: 12288
      disks: [100]
      image_id: 4b1e1bce-72b6-49e2-9acb-95570ce33b8a
      wait: no
    delegate_to: localhost

